### ISSUE TITLE
Add motion sensor

### ISSUE THREAD

**Issue by pniewiadowski** [crserran/home-alarm#2]
I think would be good to add not only windows/doors sensor, but motion sensor as well.
These can trigger an alarm as well.

**Comment by crserran** [comment]
Hi @pniewiadowski , thank you for your comment.

It’s a great idea to include this functionality to the project, I was thinking in that for the nexts releases.

The behavior would be like: 
If alarm has been fired and the motion detector continue detecting movement, the alarm won’t be stopped until the motion stops and ‘stop_delay’ finishes.

If you have any suggestion about that will be welcome 🙂

**Comment by jactora** [comment]
add a feature:
if safe mode ON, motionsensordetected, then alarm activated

**Comment by xaviml** [comment]
Hi @jactora,

I think that is the whole purpose of Home Alarm. Documentation says:

```
If the safe mode is active and some of windows or doors are opened, the user has a few seconds to indentify himself into the system.
```

And in fact, I have tried it and that is the behavior. If a window or door is open and safe mode is not active, then it won't fire the alarm. However, if the safe mode is on and a motion sensor is detected, then you have X seconds to identify yourself (turn off the safe mode) or otherwise, the alarm will go off.

**Comment by jactora** [comment]
@xaviml 
sorry not sure if you got my feature request.
i requested a new feature to be added - for motion sensor too just like door n window sensor.

**Comment by xaviml** [comment]
Hi @jactora,

This is what @pniewiadowski already proposed then. However, I would like to add to this issue that if you add the motion sensor in the list of sensors, it should work. Motion sensors are binary_sensors like the ones for windows and doors.

Cheers,

**Comment by jactora** [comment]
thanks @xaviml 
you are great. it worked

**Comment by crserran** [comment]
I close the issue due to the new Release v2.0.0. Many thanks :)
