### ISSUE TITLE
Using Home Alarm as an Action in HA Automations

### ISSUE THREAD

**Issue by titelies** [crserran/home-alarm#5]
I have setup an HA automation that uses Alexa Guard as a trigger and Home Alarm as as action... I currently have an automation setup so when the Alexa Guard state changes from disarmed to armed_away, then the Action type Condition > State > input_boolean.safe_mode to on (but the action never happens). And vice versa, when the Alexa Guard state changes from armed_away to disarmed the Action type Condition > State > input_boolean.safe_mode to off (doesn't work either). 
Any idea why or advice to offer....

**Comment by crserran** [comment]
Hi @titelies, I have never tried Alexa Guard so I am afraid that I cannot help you with it. Maybe is something related with automation trigger but I cannot ensure this. I could probably recommend that you write your issue on the [Home Assistant Community Forum](https://community.home-assistant.io/) and maybe somebody can help you with this topic :)
