### ISSUE TITLE
[Feature Request] Activate Switch

### ISSUE THREAD

**Issue by sreknob** [crserran/home-alarm#7]
Hi, this looks really neat! I was thinking that it would be great if you could add support to fire a switch as well as light/notifier/media_player. It would be useful for activating an actual siren or other equipment. Thanks!

**Comment by crserran** [comment]
Hi @sreknob, thank you for your suggestion. I was in holidays these days and I couldn't answer you before. 
I think it's a great idea to toggle a switch when alarm has been fired. I will implement this feature for the next release (v2.3.0).

Regards,

**Comment by crserran** [comment]
Hi @sreknob a new version has been released with the changes you proposed. You can check docs [here](https://crserran.github.io/home-alarm/alerts/switch/). 

Let me know if it is working as expected. Thank you for your support :)
